### ISSUE TITLE
hostname doesn't match fastly.net

### ISSUE THREAD

**Issue by montanaflynn** [jsdelivr/bot#38]
I just submitted a [PR](https://github.com/jsdelivr/jsdelivr/pull/4306) for my human-date library and got this error:

    Looks like the info.ini has a few problems:
        hostname 'www.npmjs.com' doesn't match either of 'a.sni.fastly.net', 'a.sni.global-ssl.fastly.net'

I didn't see anything about fastly anyhwere in the CONTRIBUTING section or here in existing issues. Please advise on next course of action.

**Comment by megawac** [comment]
That's because [http://docs.python-requests.org/en/latest/](http://docs.python-requests.org/en/latest/) fails to validate the https certificate. There is little I can do about this
