### ISSUE TITLE
JSON incorrectly passing

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/bot#40]
The bot considers this as correct
```
{
  "packageManager": "github",
  "name": "jdenticon",
  "repo": "dmester/jdenticon",
  "files": {
    "basePath": "dist/",
    "exclude": "jdenticon.js"
  }
}
```
while its not and libgrabber will fail.
The correct is `"exclude": ["file"]`

**Comment by megawac** [comment]
Want to make a spec of things you want validated in regards to the
update.json file?

**Comment by jimaek** [comment]
exclude and include are arrays, so the bot will fail to update the project in its current form
