### ISSUE TITLE
info.ini error where info.ini is present

### ISSUE THREAD

**Issue by kahwee** [jsdelivr/bot#43]
The bot says "viewability has no info.ini file buddy"

https://github.com/jsdelivr/jsdelivr/pull/5068

Any idea what's wrong?

**Comment by jimaek** [comment]
The API took a bit longer to update. Nothing to worry, it wont happen again

**Comment by drinckes** [comment]
It happened again. :-)

jsdelivr/jsdelivr#12246

Do I need to do anything to the PR or will the bot retry on it's own? Thanks!
