### ISSUE TITLE
The bot doesn't seem to work for the lipis/bootstrap-social

### ISSUE THREAD

**Issue by lipis** [jsdelivr/bot#48]
I realised about the existence of the project when after pushing a new release for the [lipis/flag-icon-css](https://github.com/lipis/flag-icon-css) it was generating a new PR: https://github.com/jsdelivr/jsdelivr/pulls?utf8=%E2%9C%93&q=is%3Apr+flag-icon-css+

But it doesn't seem to do anything when I'm pushing to [lipis/bootstrap-social](https://github.com/lipis/bootstrap-social). Is there anything I have to do so the bot will start picking up on this project as well?

**Comment by jimaek** [comment]
You need to add an `update.json` file here https://github.com/jsdelivr/jsdelivr/tree/master/files/bootstrap-social

The documentation on how to do it is here 
https://github.com/jsdelivr/libgrabber

**Comment by lipis** [comment]
Thanks..

**Comment by lipis** [comment]
Just let me know there if that's the right way..
