### ISSUE TITLE
Bot failing with SSL error

### ISSUE THREAD

**Issue by brycekahle** [jsdelivr/bot#53]
From https://github.com/jsdelivr/jsdelivr/pull/10085
> [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

**Comment by megawac** [comment]
That's a [python-requests](http://docs.python-requests.org/en/master/)/`pyOpenSSL` issue. See https://github.com/kennethreitz/requests/issues/2022

Nothing we can do here for now
