### ISSUE TITLE
Folder structure changes reported incorrectly

### ISSUE THREAD

**Issue by soumak77** [jsdelivr/bot#64]
No changes to the folder structure were made between versions, yet the bot is reporting that there are changes: https://github.com/jsdelivr/jsdelivr/pull/13487.

Based on the error message, it looks as though the bot saw no files being committed (or at least some small subset).  Perhaps this is a timing issue and due to the large commit size, the bot is checking the file structure before all files have been copied?

**Comment by soumak77** [comment]
possibly related to https://github.com/jsdelivr/bot/issues/7

**Comment by megawac** [comment]
Yeah dupe of #7
