### ISSUE TITLE
Add an option to request re-check

### ISSUE THREAD

**Issue by zdroid** [jsdelivr/bot#65]
You basically have to submit a new PR if it fails in eyes of the bot, right? Why not add an option to recheck on request, such as "[at sign]jsdelivrbot please re-check", or "please revalidate", something like that. It'd be very helpful to reduce the PR spam.

**Comment by megawac** [comment]
@zdroid we revalidate on every new commit. The thing is the bot only posts a message on the pull request once. If you click on a `x` on a pull request commit or on details at the bottom of the pull request you'll see the full message (https://gist.github.com/jsdelivrbot/d6659f7c360330dceb0ae1cb9a631130). The reason we do this is to avoid spamming a pull request with comments

![](https://snag.gy/laO5Ii.jpg)

**Comment by zdroid** [comment]
Thanks for clarifying. :smile:

**Comment by megawac** [comment]
Sorry for late response though. I wish github allowed you to configure emails to be sent based on the repo. For example, I would not want an email every time a PR is created on jsdelivr but I would on this repo

**Comment by zdroid** [comment]
@megawac You can try making teams or something. Or just use watch plain and simple — it doesn't have specific settings but it works fine.
