### ISSUE TITLE
Allow non-lowercase chars

### ISSUE THREAD

**Issue by DiegoRBaquero** [jsdelivr/bot#67]
It would be great if the repo field in update.json allowed non-lowercase chars.

For example, my profile and some of my repos have some uppercase chars and the bot doesn't allow them.

Plus, the error is not very clear: "issues validating update.json for v: expected string or buffer"

Related: https://github.com/jsdelivr/jsdelivr/pull/16707

**Comment by jimaek** [comment]
We are redesigning jsDelivr and the new version will make this problem obsolete. It should be live in 1-2 months.
