### ISSUE TITLE
detect minified files

### ISSUE THREAD

**Issue by tomByrer** [jsdelivr/bot#9]
[ref](https://github.com/jsdelivr/bot/issues/1#issuecomment-43042075)
**Phase 1** Check [sourceMappingURL](http://regexr.com/38rgu)
`/(\/\*+[\s\S]*?sourceMappingURL\s*=[\s\S]*?\*\/)|(\/\/.*?sourceMappingURL\s*=.*?[\r\n])/g`
If there is a .map file pointed to, then likely this is a minified file.
Other tests should be skipped if true.

**Phase 2**: remove comments (where possible without trashing code)
[This RegEx test](http://regexr.com/38rft) should work: `/(^(\/\*+[\s\S]*?\*\/)|(\/\*+.*\*\/)|^\/\/.*?[\r\n])[\r\n]*/gm` on this test code:
```js
Match full line & blank newlines after: 
//! https://github.com/tomByrer/web-engeneering-notes/blob/master/banner-tips.md#mini-banner

hunk
/**
* usage: https://github.com/jsdelivr/bot/issues/1#issuecomment-42943418
**/
junk
/*! script.node.js github.com/owner/scriptjs 0.7.0 (c)2014 License GPL */
funk
End line comment=! /*** I like stars ***/

left/*middle*/right
trunk
// project-legacy.js github.com/owner/project 0.1.0 (c)2014 @licence MIT
stunk
/* @preserve this comment please? */
sunk
// @License to @Preserve: none
bunk
/* important info but not enough to keep in minified code */
punk
// comment
edge-case (works if have space between **)
/**/
space
/*
*/

Unsure what to do:
//# sourceMappingURL=jquery.mobile-1.4.2.min.map
var x=y;// Great coding!  Have to keep this comment because of above example...
var twitterHandle = '@preserve';  //oops

Should Fail:
https://user:pass@license.not-a-comment.it/is-url.js
/!escape
<!-- remove this comment -->
"/*"

True; EOF test:
/* test */
```
Bonus: grabs newlines after comment.

**Phase 3**
```
If ( comments-removed.match(/\n\r/g).length > ( comments-removed.length / 80 ) {
  not mified 
}
```

**Comment by megawac** [comment]
I think https://github.com/jsdelivr/bot/commit/512d35252206ac673a13a9a28af05b6d94af5b36 is a reasonable fix based on average line lengths. Essentially I assume if a file has an average line width of 200 characters we classify the file as minified
